site_name: Jianliang's Home Page
site_url: https://jianlianggao.github.io/
theme: 
  name: windmill
  locale: en
nav:
  - Home: index.md
  - About: about.md
  - Logs: 
    - 'Galaxy local Dev': '_posts/2020-02-28-Galaxy-local-deploy-docker-tool.md'
    - 'Kubernetes': '_posts/2017-07-31-KubeNow-on-Azure.md'
  - 'Posts': 
    - 'dHCP': '_posts/2018-01-21-dHCP-intro.md'
    - 'PhenoMeNal': '_posts/2017-07-21-PhenoMeNal-intro.md'
