---
layout: post
title: "Introduce to dHCP"
excerpt:  
author: "Jianliang"
date: "09 August 2018"
status: process
published: true
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## dHCP -- The Developing Human Connectome Project

The Developing Human Connectome Project (dHCP), led by King’s College London, Imperial College London and Oxford University, aims to make major scientific progress by creating the first 4-dimensional connectome of early life. Our goal is to create a dynamic map of human brain connectivity from 20 to 44 weeks post-conceptional age, which will link together imaging, clinical, behavioural, and genetic information. This unique setting, with imaging and collateral data in an expandable open-source informatics structure, will permit wide use by the scientific community, and to undertake pioneer studies into normal and abnormal development by studying well-phenotyped and genotyped group of infants with specific genetic and environmental risks that could lead to Autistic Spectrum Disorder or Cerebral Palsy.

## for more detail, please visit: <http://www.developingconnectome.org>
